name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions: {}

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Set up Rust
        run: rustup update --no-self-update

      - name: Cache cargo deps
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-lint-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Dependencies
        run: |-
          sudo apt-get update;
          sudo apt-get install --no-install-recommends \
          libasound2-dev libudev-dev libwayland-dev

      - name: Lint
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Check formatting
        run: cargo fmt --check
