name: Release

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]

env:
  BINARY: bevy-52-card-pickup

concurrency:
  group: ${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' || !startsWith(github.ref, 'refs/tags/v') }}

permissions: {}

jobs:

  # Build for wasm
  build-wasm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Get project version
        id: get_version
        shell: python
        run: |-
          from os import environ
          from tomllib import load
          with open("Cargo.toml", "rb") as f:
              cargo_toml = load(f)
              version = cargo_toml["package"]["version"]
              with open(environ["GITHUB_OUTPUT"], "a") as out:
                  out.write(f"tag={version}\n")
      - name: Setup Rust toolchain
        run: |-
          rustup update --no-self-update
          rustup target add wasm32-unknown-unknown
      - name: install wasm-bindgen-cli
        run: |
          cargo install wasm-bindgen-cli

      - name: Build
        run: |
          cargo build --release --target wasm32-unknown-unknown

      - name: Prepare package
        shell: bash
        run: |-
          wasm-bindgen --no-typescript --out-name bevy_game --out-dir wasm --target web target/wasm32-unknown-unknown/release/${BINARY}.wasm
          cp -r assets wasm/ || true # Try to copy, but ignore if it can't copy if source directory does not exist

      - name: Package as a zip
        working-directory: ./wasm
        shell: bash
        env:
          ASSET_NAME: ${{ env.BINARY }}-wasm-${{ steps.get_version.outputs.tag }}.zip
        run: |
          zip --recurse-paths ../${BINARY}.zip .
          mv ../${BINARY}.zip ../${ASSET_NAME}

      - name: Upload binaries to artifacts
        uses: actions/upload-artifact@v6
        with:
          path: ${{ env.BINARY }}-wasm-${{ steps.get_version.outputs.tag }}.zip
          name: wasm

      - name: Prepare GH-pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./wasm/

  # Build for Linux
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Get project version
        id: get_version
        shell: python
        run: |-
          from os import environ
          from tomllib import load
          with open("Cargo.toml", "rb") as f:
              cargo_toml = load(f)
              version = cargo_toml["package"]["version"]
              with open(environ["GITHUB_OUTPUT"], "a") as out:
                  out.write(f"tag={version}\n")
      - name: Setup Rust toolchain
        run: |-
          rustup update --no-self-update
          rustup target add x86_64-unknown-linux-gnu

      - name: Install dependencies
        run: |-
          sudo apt-get update;
          sudo apt-get install \
          pkg-config \
          libx11-dev \
          libasound2-dev \
          libudev-dev \
          libxcb-render0-dev \
          libxcb-shape0-dev \
          libxcb-xfixes0-dev \
          libwayland-dev

      - name: Build
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu

      - name: Prepare package
        shell: bash
        run: |
          mkdir linux
          cp target/x86_64-unknown-linux-gnu/release/${BINARY} linux/
          cp -r assets linux/ || true # Try to copy, but ignore if it can't copy if source directory does not exist

      - name: Package as a zip
        working-directory: ./linux
        env:
          ASSET_NAME: ${{ env.BINARY }}-linux-${{ steps.get_version.outputs.tag }}.zip
        run: |
          zip --recurse-paths ../${BINARY}.zip .
          mv ../${BINARY}.zip ../${ASSET_NAME}

      - name: Upload binaries to artifacts
        uses: actions/upload-artifact@v6
        with:
          path: ${{ env.BINARY }}-linux-${{ steps.get_version.outputs.tag }}.zip
          name: linux

  # Build for Windows
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Get project version
        id: get_version
        shell: python
        run: |-
          from os import environ
          from tomllib import load
          with open("Cargo.toml", "rb") as f:
              cargo_toml = load(f)
              version = cargo_toml["package"]["version"]
              with open(environ["GITHUB_OUTPUT"], "a") as out:
                  out.write(f"tag={version}\n")
      - name: Setup Rust toolchain
        run: |-
          rustup update --no-self-update
          rustup target add x86_64-pc-windows-msvc

      - name: Build
        run: |
          cargo build --release --target x86_64-pc-windows-msvc

      - name: Prepare package
        shell: pwsh
        run: |
          mkdir windows
          cp "target/x86_64-pc-windows-msvc/release/$env:BINARY.exe" windows/
          mkdir assets -ea 0 # create the assets directory if it does not exist, it will get ignored in the zip if empty
          cp -r assets windows/

      - name: Package as a zip
        shell: pwsh
        env:
          ASSET_NAME: ${{ env.BINARY }}-windows-${{ steps.get_version.outputs.tag }}.zip
        run: |
          Compress-Archive -Path windows/* -DestinationPath "$env:BINARY.zip"
          mv "$env:BINARY.zip" "$env:ASSET_NAME"

      - name: Upload binaries to artifacts
        uses: actions/upload-artifact@v6
        with:
          path: ${{ env.BINARY }}-windows-${{ steps.get_version.outputs.tag }}.zip

  # Build for MacOS x86_64
  build-macOS-intel:
    runs-on: macOS-latest

    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Get project version
        id: get_version
        shell: python
        run: |-
          from os import environ
          from tomllib import load
          with open("Cargo.toml", "rb") as f:
              cargo_toml = load(f)
              version = cargo_toml["package"]["version"]
              with open(environ["GITHUB_OUTPUT"], "a") as out:
                  out.write(f"tag={version}\n")
      - name: Setup Rust toolchain
        run: |-
          rustup update --no-self-update
          rustup target add x86_64-apple-darwin
      - name: Environment Setup
        run: |
          export CFLAGS="-fno-stack-check"
          export MACOSX_DEPLOYMENT_TARGET="10.9"

      - name: Build
        run: |
          cargo build --release --target x86_64-apple-darwin

      - name: Prepare Package
        shell: bash
        env:
          ASSET_NAME: ${{ env.BINARY }}-macOS-intel-${{ steps.get_version.outputs.tag }}.dmg
        run: |
          mkdir -p ${BINARY}.app/Contents/MacOS
          cp target/x86_64-apple-darwin/release/${BINARY} ${BINARY}.app/Contents/MacOS/
          cp -r assets ${BINARY}.app/Contents/MacOS/ || true # Try to copy, but ignore if it can't copy if source directory does not exist
          hdiutil create -fs HFS+ -volname "${BINARY}" -srcfolder ${BINARY}.app ${BINARY}-macOS-intel.dmg
          mv ${BINARY}-macOS-intel.dmg ${ASSET_NAME}

      - name: Upload binaries to artifacts
        uses: actions/upload-artifact@v6
        with:
          path: ${{ env.BINARY }}-macOS-intel-${{ steps.get_version.outputs.tag }}.dmg
          name: macOS-intel

  # Build for MacOS Apple Silicon
  build-macOS-apple-silicon:
    runs-on: macOS-latest

    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Get project version
        id: get_version
        shell: python
        run: |-
          from os import environ
          from tomllib import load
          with open("Cargo.toml", "rb") as f:
              cargo_toml = load(f)
              version = cargo_toml["package"]["version"]
              with open(environ["GITHUB_OUTPUT"], "a") as out:
                  out.write(f"tag={version}\n")
      - name: Setup Rust toolchain
        run: |-
          rustup update --no-self-update
          rustup target add aarch64-apple-darwin
      - name: Environment
        # macOS 11 was the first version to support ARM
        run: |
          export MACOSX_DEPLOYMENT_TARGET="11"

      - name: Build
        run: |
          cargo build --release --target aarch64-apple-darwin

      - name: Prepare Package
        shell: bash
        env:
          ASSET_NAME: ${{ env.BINARY }}-macOS-apple-silicon-${{ steps.get_version.outputs.tag }}.dmg
        run: |
          mkdir -p ${BINARY}.app/Contents/MacOS
          cp target/aarch64-apple-darwin/release/${BINARY} ${BINARY}.app/Contents/MacOS/
          cp -r assets ${BINARY}.app/Contents/MacOS/ || true # Try to copy, but ignore if it can't copy if source directory does not exist
          hdiutil create -fs HFS+ -volname "${BINARY}-macOS-apple-silicon" -srcfolder ${BINARY}.app ${BINARY}-macOS-apple-silicon.dmg
          mv ${BINARY}-macOS-apple-silicon.dmg ${ASSET_NAME}

      - name: Upload binaries to artifacts
        uses: actions/upload-artifact@v6
        with:
          path: ${{ env.binary }}-macOS-apple-silicon-${{ steps.get_version.outputs.tag }}.dmg
          name: macOS-apple-silicon
          retention-days: 1

  release-assets:
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      # needed to upload release assets
      contents: write
    needs:
      - build-wasm
      - build-linux
      - build-windows
      - build-macOS-intel
      - build-macOS-apple-silicon
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v7
        with:
          pattern: ${{ env.binary }}-*
          merge-multiple: true
          path: artifacts
      - name: List assets
        id: list-assets
        run: |-
          assets=$(ls ./artifacts)
          echo "Assets to upload: ${assets}"
          echo "artifacts=${assets}" >> "${GITHUB_OUTPUT}"
      - name: Upload binaries to release
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
          ARTIFACTS: ${{ steps.list-assets.outputs.artifacts }}
          REPO: ${{ github.repository }}
        run: >-
          gn release upload
          "${TAG}"
          --repo "${REPO}"
          ${ARTIFACTS}

  deploy-gh-pages:
    # We only want to deploy from
    # 1. This fork. Not some other fork.
    # 2. Pushes to the main
    # 3. Pull requests targeting the main branch (see triggers at top of file)
    # 4. Tags starting with "v" (to publish releases)
    if: github.repository == '2bndy5/bevy-52-card-pickup' && (github.ref == 'refs/heads/main' || github.event_name == 'pull_request' || startsWith(github.ref, 'refs/tags/v'))
    needs: build-wasm
    environment:
      name: github-pages
      url: ${{ steps.deploy-gh-pages.outputs.page_url }}
    permissions:
      # to deploy to Pages
      pages: write
      # to verify the deployment originates from an appropriate source
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
        id: deploy-gh-pages
